### ISSUE TITLE
Adding URI registry in windows from java

### ISSUE THREAD

**Issue by DhyanCoder** [maxandersen/starfish#2]
To create URI registry in windows we can create a starfish.reg file and run 'reg import starfish.reg' from cmd but it requires administrator rights
we can run following code from java program
`Runtime.getRuntime().exec("reg import starfish.reg");`
but it failed
I've tried multiple methods as
https://serverfault.com/questions/427368/command-line-switch-to-administrator-mode
https://superuser.com/questions/694761/how-to-run-cmd-with-admin-privileges-using-command-line
but failed

**Comment by maxandersen** [comment]
when you install something you normally require to run the app as admin in windows so i dont see a problem for the installaiton to ask user to upgrade to admin user or run it with admin rights first time

**Comment by DhyanCoder** [comment]
Okay I understand.
But this is causing error while running project in Intellij Idea
`try {
            Runtime.getRuntime().exec("reg import starfish.reg");
            System.out.println("DONE PROCESSING");
            
        } catch (Exception e) {
            e.printStackTrace();
}`
This prints `DONE PROCESSING` but there is no registry in windows registry Editor.


If I simple run `reg import starfish.reg` on cmd it print `ERROR: Error accessing the registry.`
while if i open this in cmd(admin) this command adds registry successfully.

**Comment by fahad-israr** [comment]
As an example I was able to successfully run this as mentioned here: [https://github.com/shengyou/vscode-handler](https://github.com/shengyou/vscode-handler) 

Do check this out !!

**Comment by DhyanCoder** [comment]
I am running this java app from cmd(admin) and it successfully added the registry
